apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: tetris
        image: bsord/tetris
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

#### TODO:
#### Add HPA for pod auto-scaling
#### Add PVC for storage (score?)
#### Add PDB for HA
#### Add ConfigMap for configuration
#### Add KamusSecret/SealedSecret/Secret for storing secrets
#### Add Monitor for monitoring...
#### Add service mesh configuration
#### Add....