apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "2"
commonLabels:
  app: tetris2
images:
  - name: bsord/tetris
    newName: ociotec/tetris
resources:
- ../../base
patches:
- patch-ingress-hostname.yaml