apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetris
spec:
  rules:
  - host: tetris2.localtest.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tetris2
            port: 
              number: 80