apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tetris.fullname" . }}
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tetris.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tetris.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
