apiVersion: v1
kind: Service
metadata:
  name: {{ include "tetris.fullname" . }}
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    {{- include "tetris.selectorLabels" . | nindent 4 }}
